Change LANG in install-deps.sh to en_US.UTF-8
LANG=C causes pip installation issues in CentOS 7, observed in Kolla container
image build on stable/train and earlier, see [1] for full build log:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 25:
ordinal not in range(128)

[1]: https://zuul.opendev.org/t/openstack/build/45a5a3c3c2a046f6bd1868026e1e7803/log/kolla/build/000_FAILED_bifrost-base.log#8807

Change-Id: Iff11316a0708f5df437efecf95de47bcc4579a09