scripts: install-deps: Add 'make' to the required packages
Latest paramiko pulls pynacl which requires 'make' to be present on the
host otherwise it fails with the following error:

~> pip install pynacl
Collecting pynacl
  Using cached PyNaCl-1.1.2.tar.gz
Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from pynacl)
Requirement already satisfied: cffi>=1.4.1 in ./.local/lib/python2.7/site-packages (from pynacl)
Requirement already satisfied: pycparser in ./.local/lib/python2.7/site-packages (from cffi>=1.4.1->pynacl)
Building wheels for collected packages: pynacl
  Running setup.py bdist_wheel for pynacl ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-WNVVlf/pynacl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');
f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpCBHg6Lpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/nacl
[...]
    checking for nanosleep... yes
    checking for posix_memalign... yes
    checking for getpid... yes
    checking if gcc/ld supports -Wl,--output-def... not needed, shared libraries are disabled
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating dist-build/Makefile
    config.status: creating libsodium.pc
    config.status: creating libsodium-uninstalled.pc
    config.status: creating msvc-scripts/Makefile
    config.status: creating src/Makefile
    config.status: creating src/libsodium/Makefile
    config.status: creating src/libsodium/include/Makefile
    config.status: creating src/libsodium/include/sodium/version.h
    config.status: creating test/default/Makefile
    config.status: creating test/Makefile
    config.status: executing depfiles commands
    config.status: executing libtool commands
    error: [Errno 2] No such file or directory

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-WNVVlf/pynacl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-PAHH7o-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-WNVVlf/pynacl/

The problem has also been reported to the project page on github to
improve the cryptic error message.

This also updates the list of required host packages

Link: https://github.com/pyca/pynacl/issues/298
Change-Id: I25031182379eb723cc0a15840564939122a44bd0