Fix /etc/hosts before starting the rabbitmq server
Rabbitmq server requires the hostname to be in /etc/hosts
so make sure it's there before we start the server. This fixes
the following error when /etc/hosts is badly configured:

~$ /usr/sbin/rabbitmq-server --help
ERROR: epmd error for host host-44-11-0-202: address (cannot connect to
host/port)

Change-Id: I68d8f32b20a097c496f8df597b239711f4b76ade
Signed-off-by: Markos Chandras <mchandras@suse.de>