Fix bifrost_inventory.py with no nodes enrolled
Run the bifrost_inventory.py script withBIFROST_INVENTORY_SOURCE=ironic,
and no hosts enrolled in ironic. It fails:

    RuntimeError: dictionary changed size during iteration

This change fixes the issue by using a copy of the groups dictionary.

Change-Id: I614580c37406a75eab356fdc217a3ffa052bc5ff
Story: 2007776
Task: 40002
(cherry picked from commit 3ffa9c78376f75acc418590489125a8ba0769ab0)