roles: bifrost-ironic-install: Add PyMySQL dependency for ironic-dbsync
We are using MariaDB database for ironic so we need to install
the optional PyMySQL dependency for sqlalchemy on all distributions
otherwise ironic-dbsync fails with the following error:

CRITI [ironic] ImportError: No module named pymysql
Traceback (most recent call last):
  File "/usr/bin/ironic-dbsync", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/ironic/cmd/dbsync.py", line 103, in main
    CONF.command.func()
  File "/usr/lib/python2.7/site-packages/ironic/cmd/dbsync.py", line 35, in upgrade
     migration.upgrade(CONF.command.revision)
  File "/usr/lib/python2.7/site-packages/ironic/db/migration.py", line 36, in upgrade
     return get_backend().upgrade(version)
  File "/usr/lib/python2.7/site-packages/ironic/db/sqlalchemy/migration.py", line 56, in upgrade
     alembic.command.upgrade(config, revision or 'head')
  [...]
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/dialects/mysql/pymysql.py", line 49, in dbapi
     return __import__('pymysql')
ImportError: No module named pymysql

Change-Id: Ib44779de06a7bad91a08e148e1c0e1eb9815afe8